# Generated by Django 3.2.5 on 2021-08-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blogimg',
            field=models.ImageField(default=1, upload_to='blog_img'),
            preserve_default=False,
        ),
    ]
